name: Run Geo Code Fetcher

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  schedule:
    - cron: '0 0 * * 2,5' #Runs at 00:00, only on Tuesday and Friday.

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add found_geo_codes.txt README.md
          git commit -m "Update found_geo_codes.txt and README.md"
          git push
